openapi: "3.0.3"
tags:
  - name: CHF OAuth 2.0
paths:
  /authorize:
    get:
      summary: OAuth 2.0 Authorization Endpoint
      tags:
        - CHF OAuth 2.0
      responses:
        "400":
          description: Missing required parameter, such as redirect_uri.
        "302":
          description: Redirection according to OAuth 2.0 specification.
      parameters:
      - name: client_id
        in: query
        description: The client identifier
        required: true
        schema:
          type: string
      - name: redirect_uri
        in: query
        description: The redirect URI for redirection responses
        required: true
        schema:
          type: string
      - name: response_type
        in: query
        description: The OAuth 2.0 response type - only code is accepted
        required: true
        schema:
          type: string
          enum:
          - code
      - name: state
        in: query
        description: The OAuth 2.0 state parameter
        required: false
        schema:
          type: string
  /login:
    get:
      summary: Login url
      tags:
        - CHF OAuth 2.0
      security:
        - basic: []
      responses:
        "401":
          description: Login required
  /token:
    post:
      summary: OAuth 2.0 Token Endpoint
      tags:
        - CHF OAuth 2.0
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
              - client_id
              - client_secret
              - redirect_uri
              - grant_type
              properties:
                client_id:
                  type: string
                  description: The client identifier
                client_secret:
                  type: string
                  description: The client secret
                redirect_uri:
                  type: string
                  description: The redirect URI used in the authorization request
                grant_type:
                  type: string
                  description: The OAuth 2.0 grant type - must be authorization_code
                  enum:
                  - authorization_code
      responses:
        "400":
          description: Bad request data, according to OAuth 2.0 specification
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The OAuth 2.0 error code.
  /api:
    get:
      summary: Get the username from the token
      tags:
        - CHF OAuth 2.0
      security:
        - oauth2: []
      responses:
        "200":
          description: Successful response containing the username from the bearer token
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: string
                    description: The username
        "401":
          description: Could not validate the bearer token.
components:
  securitySchemes:
    login:
      type: http
      scheme: basic
      description: Basic authentication for login - try password = username!
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: BASE_URL/authorize
          tokenUrl: BASE_URL/token
          scopes:
            test: A simple scope - not required.
